### PR TITLE
Make all loaders/plugins optional

### PR DESCRIPTION
**Pull request by lukekarrys**
This addresses the discussion started here: https://github.com/HenrikJoreteg/hjs-webpack/issues/26#issuecomment-138604767

This makes everything optional, so the only peer dependency left is `webpack-dev-server`.

One quirk is that since the css related loaders are chained, I opted to throw an error if some of the loaders are installed but not others. This is also specified in the documentation.

Ref #26

### CODE REVIEW

**Comment by lukekarrys** [comment]
Also, I'd like to publish this as a prerelease beta since its a major version update after I get some :eyes: on it.

**Comment by latentflip** [comment]
+1 this would fix the issues we've had on a client project where react-hot-loader breaks ampersand, but is installed automatically by npm2 since it's a peerDep.

**Comment by lukekarrys** [comment]
Also this fixes issues I've had where I run `npm ls` as a validation step in my projects using npm3. The peer deps are no longer automatically installed but `npm ls` will still error as they are expected.

**Comment by lukekarrys** [comment]
If anyone wants to test this (cc @latentflip) you can run `npm install hjs-webpack@3.0.0-beta3 --save-dev`. It's probably best to clear our the dependencies from `node_modules` and `package.json` that were hjs-webpack's peerDeps to properly mimic what a new install of v3 will look like.

**Comment by HenrikJoreteg** [comment]
I love it. This needs to happen.

**Comment by fyockm** [comment]
Great work here. One recommendation from someone who's not overly familiar with `webpack`... I think it would be a huge help to provide some description of each of those now-optional plugins. Obviously, I could go research each individually, and certainly would if I choose to use it. However, it would be very beneficial from a developer prospective if there was a one liner in the README explaining why I might want to dig deeper on a particular plugin.

```
autoprefixer babel-loader css-loader json-loader postcss-loader react-hot-loader style-loader stylus-loader url-loader yeticss
```

**Comment by lukekarrys** [comment]
@fyockm that's a great idea! I'll do that before merging.

**Comment by lukekarrys** [comment]
Published as `v3.0.0`

**Comment by latentflip** [comment]
Awesome work @lukekarrys, love it!

Sorry I didn't get a chance to try it in rc :)

**Comment by chrisvfritz** [comment]
@lukekarrys @HenrikJoreteg I'm working on building off this for #67, but since [`npm link` doesn't play nice with peer dependencies](https://github.com/npm/npm/issues/5875), I was wondering if there were any development suggestions. Specifically, the `is-installed` module will not correctly detect modules installed by the parent project. :disappointed:

**Pull request merged**
