### PR TITLE
add optional support for more compile-to-JS languages

### LINKED ISSUE #67: Add support for other transpile-to-JS languages
Would there be significant overhead to add support for other popular transpile-to-JS languages? The three popular ones that come to mind are:

- CoffeeScript (there's a [loader supporting JSX](https://github.com/KyleAMathews/cjsx-loader))
- TypeScript (1.6 beta [supports JSX natively](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx))
- LiveScript (no need for JSX support, as its syntax removes the need for it - [for example](https://github.com/lansingcodes/www/blob/master/app/components/contact.ls))

### PR DESCRIPTION
**Pull request by chrisvfritz**
Resolves #67, including my personal favorite LiveScript, @jest's preferred setup with CJSX, then also CoffeeScript and TypeScript. I also DRYed up the extensions regex a little and made it more consistent.

### CODE REVIEW

**Comment by lukekarrys** [comment]
Looks great, thanks @chrisvfritz!

One thing, do you think you could add links to the new loaders along with what extensions they match to the documentation section [here](https://github.com/HenrikJoreteg/hjs-webpack#jsjsxjson)?

**Comment by chrisvfritz** [comment]
@lukekarrys You betcha. I'll try to update this PR tomorrow.

**Comment by HenrikJoreteg** [comment]
+1 w/ added docs.

**Comment by chrisvfritz** [comment]
Docs added. Also added SVG to the list of supported images extensions.

**Comment by lukekarrys** [comment]
Thanks again @chrisvfritz! Published as `v3.1.0`.

**Pull request merged**
