### PR TITLE
make isDev a dynamic default based on command ran.

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
add clearBeforeBuild option to config.
update docs, changelog, examples accordingly.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Should verify that this works on a Windows machine before merging/publishing.

**Comment by lukekarrys** [comment]
Code looks good to me with one comment.

I think `false` is a good default for `clearBeforeBuild `, but I think it should be a major version. With the behavior switch, current users will have their build directories accumulating every version of each asset that gets compiled.

While that isn't quite "breaking" it does require a code change alongside updating which is why I think it should be a major version.

**Comment by HenrikJoreteg** [comment]
@lukekarrys this doesn't change any behavior though since before this change it doesn't clear the build dir ever.

**Comment by lukekarrys** [comment]
Oh, you're right :) I had forgotten that this behavior was previously done from the `prebuild` run-script. +1 from me!

Any luck testing on Windows yet? :)

**Comment by HenrikJoreteg** [comment]
I think I'm just going to merge, publish, then verify on windows. Should be fine :)

**Pull request merged**
