### PR TITLE
add worker loader

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
this is pretty neat, IMO. But... i'm not quite 100% on the particulars of how I added it. 

But, adding it first is what enables you to write code inside the worker as ES6, which is pretty sweet.

Feedback on code and docs appreciated.

When built, it comes out as separate chunk, just like fonts, etc.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
I just realized `worker-loader` has an inline option: https://github.com/webpack/worker-loader/blob/master/createInlineWorker.js

It will try to inline and load the worker via `Blob` interface as per: http://stackoverflow.com/a/6454685/107722

Which is super awesome. But i could also see wanting to support either inlining or not. Perhaps inlining is a good default? But how could we support both?

One option would be to do: 

```
{
  pkg: 'worker-loader',
  config: {
    test: /\.?worker\.js$/,
    exclude: /node_modules/,
    loaders: ['worker-loader']
  }
},
{
  pkg: 'worker-loader',
  config: {
    test: /\.?thread\.js$/,
    exclude: /node_modules/,
    loaders: ['worker-loader?inline']
  }
},
```

What do think @lukekarrys ?

**Comment by HenrikJoreteg** [comment]
Also, it's worth noting that it falls back to loading via URL if inlining fails, so during build, it still produces a separate file. It's just never downloaded separately unless inlining fails.

**Comment by HenrikJoreteg** [comment]
The more I think about it I really like calling it `thread` since in inlined WebWorker is pretty much exactly that.

**Comment by HenrikJoreteg** [comment]
Also, I really don't think this should be something handled just by url/file loaders as it's very different than other resources, this is the main JS logic and I wouldn't want it to be subject to same limits as defined by url loader, etc. 

I'd prefer a simple mechanism for developer to determine whether they want an inlined worker or lazily loaded worker.

**Comment by HenrikJoreteg** [comment]
I've been thinking about this some more, i'm pretty happy with this the way it is, think i'm going to do it you opposed at all @lukekarrys?

**Comment by lukekarrys** [comment]
Looks good to me, with one tweak.

What about making the regex so it matches `worker.js` OR `ANYTHING.worker.js` by changing the test to `/(^|\.)worker\.js$/`? Right now something like `networker.js` would match the regex. (Same with the thread although I couldn't think of any words that ended in "thread" :smile:)

**Comment by HenrikJoreteg** [comment]
@lukekarrys good call, will do

**Comment by lukekarrys** [comment]
After that, merge away! (and I'm excited to see the awesome stuff you do with this :smile:)

**Comment by HenrikJoreteg** [comment]
yeah... I'm super excited about this :)

**Pull request merged**
