### PR TITLE
Remove HMRE and allow vanilla HMR

### LINKED ISSUE #188: Allow vanilla hmr
After reading https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf and checking out https://github.com/reactjs/redux/pull/1455/files we should make this at least possible with hjs-webpack even if it's not something that can be configured directly.

I think right now we reset `hot` based on if no hot reloading modules are installed. Also we should see if the no errors module should be removed in this case.

### PR DESCRIPTION
**Pull request by imranismail**
This should close #188

### CODE REVIEW

**Comment by lukekarrys** [comment]
I don't think we should remove the ability to use `babel-preset-react-hmre` or `babel-plugin-react-transform` (+ the other connected modules) out of the box. They can still useful in some cases I think.

Could this be updated to keep those, but still allow vanilla HMR? The way I envisioned it, if the proper loaders were not installed the function would return early but not reset `config.devServer.hot = false` in case the user still wanted to use HMR in some other way.

**Comment by imranismail** [comment]
Sure! I'll try to come up with something tonight

**Comment by imranismail** [comment]
If we don't reset the `config.devServer.hot = false` we still need to check for `redbox-react` and `babel-preset-react`. Plus plugins has to include `new webpack.HotModuleReplacementPlugin()`

**Comment by HenrikJoreteg** [comment]
Perhaps we should just leave HMR on all the time as part of the base, people could explicitly turn it off if they want, but I feel like that would be the exception, not the rule.

**Comment by HenrikJoreteg** [comment]
I mean, a big part of the reason people use this... at least I think, is to get free style hotloading just working out of the box sans plugins. Seems like a logical default to leave on and then if people really wanted to turn it off they could configure it directly by passing a devServer option.

**Comment by lukekarrys** [comment]
> Perhaps we should just leave HMR on all the time

Yeah, I agree. With the number of different ways and reasons people would use HMR I think we should remove the checking of which loaders/plugins are installed, and instead just add the `entry` and `HotModuleReplacementPlugin` if `config.hot` is set to true (which it is by default).

**Comment by imranismail** [comment]
@lukearrys something like this?

```js
var webpack = require('webpack')
var path = require('path')

function load (config) {
  // add hot loading clientside code
  config.entry.unshift(
    // Full path to webpack-hot-middleware so it works in npm2 and npm3
    path.join(path.dirname(require.resolve('webpack-hot-middleware')), 'client')
  )

  // add dev plugins
  config.plugins = config.plugins.concat([
    new webpack.HotModuleReplacementPlugin()
  ])
}

module.exports = {
  load: load
}
```

**Comment by lukekarrys** [comment]
@imranismail Looks good to me! :+1:

**Comment by lukekarrys** [comment]
@imranismail Also after reading [this comment](https://github.com/reactjs/redux/pull/1455#commitcomment-16677786) and the [short term fixes here](https://github.com/gaearon/react-transform-boilerplate/issues/122) I think it'd be best to leave in the `NoErrorsPlugin` by default.

**Comment by imranismail** [comment]
I've submitted the changes in another PR, gonna leave this fork untouched for now.

**Pull request closed without merging**
