### PR TITLE
support less-loader

### PR DESCRIPTION
**Pull request by Thr1ve**
Just a thought! Feel free to ignore :)

### CODE REVIEW

**Comment by lukekarrys** [comment]
I use less on most of my projects, so I'm a +1 on this. I also think there's a way to use `autoprefixer-core` for all css (and not have to include the plugins for stylus and less separately) which would be nice.

**Comment by lukekarrys** [comment]
My above comment isn't about changing anything in this PR, just a thought I had while reading it :smile:

**Comment by HenrikJoreteg** [comment]
I'm tempted to add a few loaders for specific things, like Less, Sass, and Jade. But perhaps not list them as peer dependencies. Since they're not directly required if we did that it should Just Work™ if you require a `.less` file and install the dependency.

**Comment by HenrikJoreteg** [comment]
Thanks for this @Thr1ve. It'll be pre-configured but not installed by default. Your commit is now included in this PR that also adds some docs: https://github.com/HenrikJoreteg/hjs-webpack/pull/11

**Comment by HenrikJoreteg** [comment]
released as `2.1.0`, @Thr1ve you'll just have to manually install `less-loader` as described here: https://github.com/henrikjoreteg/hjs-webpack#other-loaders cheers!

**Pull request closed without merging**
