### PR TITLE
Conditionally adding hot-loader to coffee in addition to jsx

### PR DESCRIPTION
**Pull request by jasonrose**
This addresses https://github.com/HenrikJoreteg/hjs-webpack/issues/123, I believe.

I say I believe because I'm having trouble testing my module via `npm link`.  I tested it by editing the `npm install`ed index.js in my node_modules directory.

### CODE REVIEW

**Comment by jasonrose** [comment]
This adds `react-hot` to `coffee-loader` and `cjsx-loader` entries alongside `babel-loader`, which was hardcoded before this pr.

**Comment by lukekarrys** [comment]
Thanks @jasonrose! We need to figure out the best way to combine this with #65. As was mentioned in that issue (https://github.com/HenrikJoreteg/hjs-webpack/issues/65#issuecomment-166698500) using the new `babel-plugin-react-transform` stuff will not work for `coffee-loader`. I'd personally like to keep support for `react-hot-loader` and the new babel transform stuff, and can hopefully figure that out once I have some time to review this and #117.

**Comment by jasonrose** [comment]
Ok, I'll implement the change in my webpack.config.js and wait.

**Comment by jasonrose** [comment]
If anybody else wants hot loading for their cjsx, I added this to my webpack.config.js:

```
//somewhere above: var cfg = getConfig({...});

if(cfg.spec.isDev && cfg.spec.devServer.hot) {
  cfg.module.loaders.forEach(function (loader) {
    var loaders = loader.loaders || [];
    if (loaders.indexOf('coffee-loader') > -1) {
      loaders.unshift('react-hot');
    }
  });
}
```

**Comment by lukekarrys** [comment]
Published as `v6.1.0`.

Also as discussed in https://github.com/HenrikJoreteg/hjs-webpack/pull/117#issuecomment-169431079, `react-hot-loader` will probably be removed in `v7.0.0` with `6.x.y` being what we point people to use if they still need to use it.

**Pull request merged**
