### PR TITLE
Webpack 2 support

### LINKED ISSUE #295: webpack 2 support
Hi!

First of all - great preset - I use it both in work-related projects and for my personal ones.

I was trying to test out the `webpack 2.1.beta.27` today, and looks like you're not compatible. Fair enough really, it's still in beta - but we'd love to see support for it sometime soon (perhaps in the next major?). 

What's the status on this?

For the record, here is the errors I got when I ran `webpack` with this config:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]
 - configuration.output has an unknown property 'cssFilename'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, library?, libraryTarget?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, umdNamedDefine? }
   Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
 - configuration.resolve.extensions[0] should not be empty.
```

config: 
```javascript
require('babel-register');

const DashboardPlugin = require('webpack-dashboard/plugin');
const WebpackNotifierPlugin = require('webpack-notifier');
const getConfig = require('hjs-webpack');
const path = require('path');
const generate = require('./html/generate-index');

const config = getConfig({
    in: path.resolve('src', 'main', 'app.js'),
    out: path.resolve('app'),
    output: { hash: true },
    clearBeforeBuild: true
});

config.entry.unshift('babel-polyfill');

module.exports = config;
```

### PR DESCRIPTION
**Pull request by selbekk**
This pull request adds support for webpack 2 configs instead of the deprecated 1.x version.

Still a bit rough around the edges code style wise, but it looks like it's working quite nice.

Very open to suggestions as well as criticism - this might be my largest PR to OSS to date :) 

Fixes #295

### CODE REVIEW

**Comment by ivarni** [comment]
I can probably help out with some end-user testing this weekend

**Comment by selbekk** [comment]
When do you think you'll have time to have a look @HenrikJoreteg?

**Comment by Benvorth** [comment]
+1

**Comment by HenrikJoreteg** [comment]
@selbekk thanks for tackling this! Upon visual review of the code it all makes sense and looks great.  I've been too busy to do much with OSS in the past year, but the last thing I want to do is be a blocker, so I'd much rather add contributors to get myself out of the way. I went ahead and added you as a contributor, I'd say feel free to merge this yourself.

My only caveat is that since @lukekarrys has been doing much of the maintenance here, it'd be great to get a +1 from him.  But as far as I'm concerned 🚢  it!

**Comment by lukekarrys** [comment]
Yes, please :shipit:! I've very much fallen behind on this repo, so I'm definitely happy to have a few more contributors. Thanks for all the work on this @selbekk!

I'd say merge and publish to npm! Just for reference I usually use the [`np`](https://github.com/sindresorhus/np) package to publish this to npm, but whatever works.

Thanks again!

**Comment by HenrikJoreteg** [comment]
@lukekarrys awesome, I added you as a contributor on npm too @selbekk. Happy publishing!

**Comment by selbekk** [comment]
Awthanks you guys - hugely appreciate it. I'll get on with merging this tonight then :)

**Pull request merged**
